server:
  port: 8080

spring:
  application:
    name: demo

  datasource:
    url: jdbc:mysql://localhost:3306/demo?serverTime=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234